# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT

from __future__ import annotations

from enum import StrEnum


class NodeKind(StrEnum):
    HUMAN = "HUMAN"
    ORGANIZATION = "ORGANIZATION"
    AGENT = "AGENT"
    MODEL = "MODEL"
    IDENTITY = "IDENTITY"
    CREDENTIAL = "CREDENTIAL"
    TOOL = "TOOL"
    MCP_SERVER = "MCP_SERVER"
    API = "API"
    SERVICE = "SERVICE"
    DATABASE = "DATABASE"
    FILESYSTEM = "FILESYSTEM"
    DATASET = "DATASET"
    SECRET = "SECRET"
    NETWORK = "NETWORK"
    POLICY = "POLICY"
    APPROVAL = "APPROVAL"
    EXECUTION_GRANT = "EXECUTION_GRANT"
    EXTERNAL_SYSTEM = "EXTERNAL_SYSTEM"
    EVIDENCE_STORE = "EVIDENCE_STORE"


class EdgeKind(StrEnum):
    CAN_CALL = "CAN_CALL"
    CAN_READ = "CAN_READ"
    CAN_WRITE = "CAN_WRITE"
    CAN_EXECUTE = "CAN_EXECUTE"
    CAN_DELEGATE = "CAN_DELEGATE"
    HAS_AUTHORITY = "HAS_AUTHORITY"
    DEPENDS_ON = "DEPENDS_ON"
    TRUSTS = "TRUSTS"
    REVEALS = "REVEALS"
    CAUSES = "CAUSES"
    TRANSFORMS = "TRANSFORMS"
    REQUIRES = "REQUIRES"
    APPROVED_BY = "APPROVED_BY"
    SCOPED_TO = "SCOPED_TO"
    DERIVED_FROM = "DERIVED_FROM"
