# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT
"""Gate 4 — consequence and envelope semantic enums."""

from __future__ import annotations

from enum import StrEnum


class EnvelopeStatus(StrEnum):
    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"


class ConsequenceReachability(StrEnum):
    """How a consequence appears in the bounded envelope (not authorization)."""

    POSSIBLE = "POSSIBLE"
    SUPPORTED = "SUPPORTED"
    UNKNOWN = "UNKNOWN"
    NOT_DERIVED = "NOT_DERIVED"


class ConsequenceKind(StrEnum):
    STATE_CHANGE = "STATE_CHANGE"
    RESOURCE_CHANGE = "RESOURCE_CHANGE"
    INFORMATION_DISCLOSURE = "INFORMATION_DISCLOSURE"
    CREDENTIAL_EXPOSURE = "CREDENTIAL_EXPOSURE"
    PRIVILEGE_CHANGE = "PRIVILEGE_CHANGE"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"
    FINANCIAL_EFFECT = "FINANCIAL_EFFECT"
    DATA_MUTATION = "DATA_MUTATION"
    DATA_DELETION = "DATA_DELETION"
    SERVICE_DISRUPTION = "SERVICE_DISRUPTION"
    IDENTITY_EFFECT = "IDENTITY_EFFECT"
    MULTI_AGENT_EFFECT = "MULTI_AGENT_EFFECT"
    PERSISTENCE_EFFECT = "PERSISTENCE_EFFECT"
    SECRET_DISCLOSURE = "SECRET_DISCLOSURE"
    CREDENTIAL_DISCLOSURE = "CREDENTIAL_DISCLOSURE"
    PII_DISCLOSURE = "PII_DISCLOSURE"
    CROSS_BOUNDARY_DISCLOSURE = "CROSS_BOUNDARY_DISCLOSURE"
    DERIVED_SENSITIVE_INFORMATION = "DERIVED_SENSITIVE_INFORMATION"
    UNKNOWN_INFORMATION_HAZARD = "UNKNOWN_INFORMATION_HAZARD"


class Reversibility(StrEnum):
    REVERSIBLE = "REVERSIBLE"
    CONDITIONALLY_REVERSIBLE = "CONDITIONALLY_REVERSIBLE"
    IRREVERSIBLE = "IRREVERSIBLE"
    UNKNOWN = "UNKNOWN"


class CausalRuleFamily(StrEnum):
    DIRECT_EFFECT = "DIRECT_EFFECT"
    PROPAGATED_EFFECT = "PROPAGATED_EFFECT"
    DEPENDENCY_EFFECT = "DEPENDENCY_EFFECT"
    INFORMATION_PROPAGATION = "INFORMATION_PROPAGATION"
    CREDENTIAL_PROPAGATION = "CREDENTIAL_PROPAGATION"
    MULTI_AGENT_PROPAGATION = "MULTI_AGENT_PROPAGATION"
    RESOURCE_DEPENDENCY = "RESOURCE_DEPENDENCY"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"
    REVERSIBILITY_RULE = "REVERSIBILITY_RULE"
    CAPABILITY_BRIDGE = "CAPABILITY_BRIDGE"
