# Build the browser application in an isolated, immutable frontend stage. The
# generated bytes are copied into the Python package before wheel creation.
FROM node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32 AS web-builder

# Sovereign dashboard sources import repo-root sdk/ and contracts/ paths
# (see web/src/features/sovereign/*). The web/ directory alone is insufficient.
WORKDIR /repo
COPY web/package.json web/package-lock.json ./web/
WORKDIR /repo/web
RUN npm ci
WORKDIR /repo
COPY web ./web
COPY sdk ./sdk
COPY contracts ./contracts
WORKDIR /repo/web
RUN npm run build -- --outDir /web-dist

# The human-readable tag documents the intended update line; the digest makes
# the actual build input immutable for supply-chain reproducibility / OpenSSF
# Pinned-Dependencies. Update both together after reviewing a new upstream
# Python image.
FROM python:3.12-slim@sha256:7a8b475003c4fe15a2cd4e55e5cfc2f3560bdc9333d624f24cdd6d4340fd7a17 AS builder

WORKDIR /build
RUN pip install --upgrade pip build
COPY pyproject.toml README.md LICENSE alembic.ini ./
COPY migrations/ ./migrations/
COPY src/ ./src/
COPY --from=web-builder /web-dist/ ./src/responsibleai/dashboard/static/whitepact/
RUN python -m build --wheel --outdir /dist


FROM python:3.12-slim@sha256:7a8b475003c4fe15a2cd4e55e5cfc2f3560bdc9333d624f24cdd6d4340fd7a17 AS runtime

ARG WHITEPACT_VERSION=1.3.1

LABEL org.opencontainers.image.title="WhitePact Governance Platform"
LABEL org.opencontainers.image.description="Runtime governance between AI agents and action"
LABEL org.opencontainers.image.version=$WHITEPACT_VERSION
LABEL org.opencontainers.image.licenses="MIT"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    WHITEPACT_HOST=0.0.0.0 \
    WHITEPACT_PORT=8765 \
    WHITEPACT_LOG_JSON=true \
    WHITEPACT_DB_PATH=/data/responsibleai.db

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1001 appgroup && \
    useradd --uid 1001 --gid appgroup --shell /bin/sh --create-home appuser

RUN mkdir -p /data && chown appuser:appgroup /data

WORKDIR /app
COPY --from=builder /dist/*.whl /tmp/
# Install via the wheel's own [dashboard,postgres,redis,billing] extras
# (defined in pyproject.toml) rather than a hand-maintained package list —
# the previous hardcoded list silently drifted out of sync with
# pyproject.toml's dashboard extra (missing sqlalchemy, aiosqlite,
# websockets, prometheus-client, cryptography, pyotp) because nothing had
# actually built and run this exact image since MFA/field-encryption
# shipped. Extras-based install can't drift the same way again.
RUN whl="$(ls /tmp/*.whl)" && pip install --no-cache-dir "${whl}[dashboard,postgres,redis,billing]"

COPY src/responsibleai/dashboard/static/ /app/static/
COPY alembic.ini ./
COPY migrations/ ./migrations/

USER appuser

EXPOSE 8765 8766

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -fsS http://localhost:8765/api/health | python3 -c "import sys,json; d=json.load(sys.stdin); sys.exit(0 if d['status'] in ('healthy','degraded') else 1)"

CMD ["sh", "-c", "uvicorn responsibleai.dashboard.app:app \
    --host ${WHITEPACT_HOST} \
    --port ${WHITEPACT_PORT} \
    --workers ${WHITEPACT_WORKERS:-1} \
    --no-access-log"]
