// Copyright (c) 2026 Guruprasath Annadurai
// SPDX-License-Identifier: MIT
import { ArrowLeft, ArrowRight, Check, ExternalLink, Mail, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Brand } from "../../components/Brand";
import { Seo } from "../../components/Seo";
import commerce from "../../content/commerce.json";
import { PricingCards } from "./PricingCards";

function PublicHeader() { return <header className="subpage-nav"><Brand /><nav aria-label="Page navigation"><Link to="/">Home</Link><Link to="/docs">Docs</Link><Link to="/trust">Trust</Link><Link to="/contact">Contact</Link><Link className="wp-button wp-button--primary" to="/signup">Create account</Link></nav></header>; }
export function PublicFooter() { return <footer className="subpage-footer"><Brand compact /><p>Runtime governance for autonomous intelligence.</p><nav aria-label="Public footer"><Link to="/pricing">Pricing</Link><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link><Link to="/refund-policy">Refund Policy</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/trust">Trust Center</Link><a href="https://github.com/Guruprasath-Annadurai/Whitepact/blob/main/SECURITY.md">Security</a><a href="https://github.com/Guruprasath-Annadurai/Whitepact">GitHub</a></nav></footer>; }

export function LegalPage({ kind }: { kind: Exclude<keyof typeof commerce, "home"> }) {
  const page = commerce[kind];
  return <div className="subpage"><Seo title={page.title} description={page.description} path={page.path} /><PublicHeader /><main className="editorial-page"><p className="page-kicker">{kind === "pricing" ? "Digital software and services" : "WhitePact · Policies"}</p><h1>{page.heading}<span>.</span></h1><p className="page-lead">{page.description}</p>{kind === "pricing" && <PricingCards />}{page.sections.map(([title, copy], index) => <section key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}<a className="text-link" href="mailto:annaduraiguruprasath7@gmail.com">Contact WhitePact <Mail size={15} /></a>{kind !== "refund-policy" && <p><Link className="text-link" to="/refund-policy">Read the Refund Policy <ArrowRight size={15} /></Link></p>}</main><PublicFooter /></div>;
}

export function DocsPage() {
  const sections = [
    ["What WhitePact does", "WhitePact evaluates supported actions routed through its configured API or MCP enforcement path and may require approval before a configured execution path proceeds."],
    ["Authentication", "Create a test API key in the customer console. Send it only from trusted server-side code as a Bearer credential. Never embed it in browser code, logs or source control."],
    ["API-key lifecycle", "The secret is shown once. Rotation creates a new secret and revokes the previous key; revocation permanently disables the selected key."],
    ["Approval and denial", "governance_approval_required means the action has not executed. A denied request remains denied and creates no client-side authority."],
    ["Evidence lookup", "Use the console Evidence page for records returned to the signed-in organization, or the authenticated evidence endpoints in the generated API reference."],
    ["UNKNOWN outcomes", "governance_unknown_outcome means WhitePact cannot confirm whether the downstream effect occurred. Do not retry automatically; inspect evidence and reconcile the external system first."],
  ];
  const apiExample = 'curl -X POST https://YOUR_WHITEPACT_HOST/api/v1/governance/tools/call \\\n  -H "Authorization: Bearer $WHITEPACT_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"YOUR_REGISTERED_TOOL","arguments":{},"purpose":"declared-purpose"}\'';
  const mcpExample = '{\n  "mcpServers": {\n    "whitepact": {\n      "url": "https://YOUR_WHITEPACT_HOST/mcp",\n      "headers": { "Authorization": "Bearer $WHITEPACT_API_KEY" }\n    }\n  }\n}';
  return <div className="subpage"><Seo title="Developer Documentation | WhitePact" description="Connect supported API and MCP actions to WhitePact's configured governance boundary." path="/docs" /><PublicHeader /><main className="docs-page"><p className="page-kicker">V1 developer entry</p><h1>Route supported actions<br />through a governed boundary<span>.</span></h1><p className="page-lead">These examples describe implemented V1 interfaces. The generated API reference remains the source for exact schemas.</p><div className="docs-grid docs-grid--reference">{sections.map(([title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h2>{title}</h2><p>{copy}</p></article>)}</div><section className="docs-example"><div><p className="page-kicker">Basic authenticated request</p><h2>Call a governed tool from server-side code</h2></div><pre><code>{apiExample}</code></pre></section><section className="docs-example"><div><p className="page-kicker">MCP connection</p><h2>Use the deployed Streamable HTTP endpoint</h2><p>Configure your MCP client for <code>/mcp</code> and provide the scoped key through its secure authorization mechanism. Verify the deployed host and configuration before use.</p></div><pre><code>{mcpExample}</code></pre></section><section className="code-entry"><div><h2>Exact schemas and operational setup</h2><p>Review the generated API reference for current request and error schemas. Use the repository quick start for local deployment and MCP configuration.</p></div><a className="wp-button wp-button--secondary" href="/api/docs">Open API reference <ArrowRight /></a><a className="wp-button wp-button--secondary" href="https://github.com/Guruprasath-Annadurai/Whitepact#quick-start">Repository quick start <ArrowRight /></a></section></main><PublicFooter /></div>;
}

export function AboutPage() { return <div className="subpage"><Seo title="About WhitePact" description="Why WhitePact exists: to keep autonomous action inside explicit human authority." path="/about" /><PublicHeader /><main className="editorial-page"><p className="page-kicker">Company and project</p><h1>Autonomy needs<br />an enforceable pact<span>.</span></h1><p className="page-lead">WhitePact is an open-source-first runtime governance project created to make autonomous systems accountable before they change the world around them.</p>{[["Mission", "Keep agent action inside verified identity, explicit authority, stated purpose, applicable policy and human-approved risk."], ["Operating principle", "Evidence before assertion. A control is described as implemented only when its enforcement path and tests exist."], ["Commercial status", "Community software is available today. Hosted commercial capability is offered only when the required production configuration and agreement are active."]].map(([title,copy],i)=><section key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}</main><PublicFooter /></div>; }

export function ContactPage() { return <div className="subpage"><Seo title="Contact WhitePact" description="Current contact paths for WhitePact evaluation, security disclosure and open-source support." path="/contact" /><PublicHeader /><main className="contact-page"><p className="page-kicker">Current contact paths</p><h1>Evaluate WhitePact<br />for your architecture<span>.</span></h1><p className="page-lead">WhitePact does not currently represent this contact path as a staffed support desk or an SLA-backed service.</p><div className="contact-grid"><article><Mail /><h2>Product evaluation</h2><p>Architecture, deployment and commercial questions through the currently published project contact.</p><a href="mailto:annaduraiguruprasath7@gmail.com?subject=WhitePact%20evaluation">Start an evaluation inquiry <ArrowRight /></a></article><article><ShieldCheck /><h2>Security disclosure</h2><p>Report suspected vulnerabilities through the published coordinated disclosure process.</p><a href="https://github.com/Guruprasath-Annadurai/Whitepact/blob/main/SECURITY.md">Security contact <ArrowRight /></a></article><article><ExternalLink /><h2>Open-source support</h2><p>Use GitHub Discussions and Issues for reproducible community questions and defects.</p><a href="https://github.com/Guruprasath-Annadurai/Whitepact">Open repository <ArrowRight /></a></article></div></main><PublicFooter /></div>; }

export function TrustCenterPage() {
  const areas = [["Security architecture", "Layered application, transport and deployment controls."], ["Identity & access", "Human sessions and machine credentials use separate trust paths."], ["Tenant isolation", "Organization scope is enforced in backend data access."], ["API-key security", "One-time disclosure, verifier storage, rotation and revocation."], ["Data protection", "Data minimization, field-encryption support and secure transport requirements."], ["Software supply chain", "Pinned automation, SBOM and provenance-oriented release controls."], ["Vulnerability management", "Coordinated disclosure and repository security checks."], ["Incident response", "Documented reporting and response procedures."], ["OpenSSF evidence", "Repository evidence only; no certification claim."], ["External review", "Independent commercial penetration test is not currently claimed."], ["Assurance status", "SOC 2: not currently certified. ISO 27001: not currently certified."], ["Known limitations", "Hosted production, legal and independent assurance gates are reported separately."]];
  return <div className="subpage trust-page"><Seo title="Trust Center | WhitePact" description="WhitePact security architecture, assurance status and known limitations." path="/trust" /><PublicHeader /><main><p className="page-kicker">Trust Center</p><h1>Controls, evidence<br />and honest boundaries<span>.</span></h1><p className="page-lead">WhitePact distinguishes implemented security controls from external certification and production validation.</p><div className="trust-grid">{areas.map(([title,copy])=><article key={title}><Check /><h2>{title}</h2><p>{copy}</p></article>)}</div></main><PublicFooter /></div>;
}

export function NotFoundPage() { return <div className="subpage"><Seo title="Page not found | WhitePact" description="The requested WhitePact page could not be found." path="/404" noIndex /><PublicHeader /><main className="not-found"><span>404</span><h1>This boundary<br />does not exist.</h1><p>The requested page was not found. Return to the WhitePact control plane.</p><Link className="wp-button wp-button--primary" to="/"><ArrowLeft /> Return home</Link></main><PublicFooter /></div>; }

export function BillingResultPage({ result }: { result: "success" | "cancelled" }) { const success = result === "success"; return <div className="subpage"><Seo title={`Billing ${result} | WhitePact`} description="WhitePact billing status." path={`/billing/${result}`} noIndex /><PublicHeader /><main className="not-found"><span>{success ? "CHECKOUT RETURNED" : "CHECKOUT CANCELLED"}</span><h1>{success ? "Payment received by Stripe." : "No subscription change was made."}</h1><p>{success ? "Your entitlement activates only after WhitePact verifies the signed Stripe webhook. Refresh Billing to see confirmed plan state." : "You can return to Billing whenever you are ready. No access is granted from a redirect alone."}</p><Link className="wp-button wp-button--primary" to="/dashboard/billing">Open billing <ArrowRight /></Link></main><PublicFooter /></div>; }
