// Copyright (c) 2026 Guruprasath Annadurai
// SPDX-License-Identifier: MIT
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, Copy, KeyRound, Plus, RefreshCw, ShieldOff, X } from "lucide-react";
import { AccessibleDialog } from "../../components/AccessibleDialog";
import { Button } from "../../components/Button";
import { api, messageFrom } from "../../lib/api";
import type { LoadState } from "../../lib/contracts";

type KeyRecord = { id: string; name: string; prefix: string; environment: string; scopes: string[]; created_at: string; last_used_at: string | null; expires_at: string | null; status: string };
type CreatedKey = KeyRecord & { api_key: string };
type Confirmation = { kind: "rotate" | "revoke"; key: KeyRecord };

export function ApiKeysPage() {
  const [keys,setKeys]=useState<KeyRecord[]>([]); const [state,setState]=useState<LoadState>("loading"); const [creating,setCreating]=useState(false); const [created,setCreated]=useState<CreatedKey|null>(null); const [confirm,setConfirm]=useState<Confirmation|null>(null); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [copyState,setCopyState]=useState<"idle"|"copied"|"failed">("idle");
  const [form,setForm]=useState({name:"",environment:"test",scopes:["governance:read"],expires_in_days:90});
  const load=useCallback(async()=>{setState("loading");setError("");try{const value=await api<{keys:KeyRecord[]}>("/api/v1/web/api-keys");setKeys(value.keys);setState(value.keys.length?"success":"empty");}catch(cause){setError(messageFrom(cause,"API keys could not be loaded"));setState("error");}},[]);
  useEffect(()=>{void load();},[load]);
  const closeCreate=useCallback(()=>setCreating(false),[]); const closeReveal=useCallback(()=>{setCreated(null);setCopyState("idle");},[]); const closeConfirm=useCallback(()=>setConfirm(null),[]);
  async function create(event:FormEvent){event.preventDefault();setBusy("create");setError("");setNotice("");const expires_at=new Date(Date.now()+form.expires_in_days*86_400_000).toISOString();try{const key=await api<CreatedKey>("/api/v1/web/api-keys",{method:"POST",body:JSON.stringify({name:form.name,environment:form.environment,scopes:form.scopes,expires_at})});setCreated(key);setCreating(false);setNotice("API key created. Copy the secret before closing the dialog.");await load();}catch(cause){setError(messageFrom(cause,"Key creation failed"));}finally{setBusy("");}}
  async function mutate(){if(!confirm)return;const {kind,key}=confirm;setBusy(kind);setError("");setNotice("");try{if(kind==="rotate"){const next=await api<CreatedKey>(`/api/v1/web/api-keys/${key.id}/rotate`,{method:"POST"});setCreated(next);setNotice("API key rotated. The previous secret is no longer valid.");}else{await api(`/api/v1/web/api-keys/${key.id}`,{method:"DELETE"});setNotice("API key revoked.");}setConfirm(null);await load();}catch(cause){setError(messageFrom(cause,kind==="rotate"?"Key rotation failed":"Key revocation failed"));setConfirm(null);}finally{setBusy("");}}
  async function copy(){if(!created)return;try{await navigator.clipboard.writeText(created.api_key);setCopyState("copied");}catch{setCopyState("failed");}}
  return <main className="dashboard-content"><div className="page-heading"><div><h1>API Keys</h1><p>Scoped machine credentials for programmatic WhitePact access.</p></div><Button disabled={Boolean(busy)} onClick={()=>setCreating(true)}><Plus aria-hidden="true"/> Create API Key</Button></div><div className="sr-live" role="status" aria-live="polite">{notice}{copyState==="copied"?" API key copied.":""}</div>{error&&<div className="form-error" role="alert">{error}</div>}
    {state==="loading"?<section className="data-panel console-state" role="status"><RefreshCw className="spin"/><h2>Loading API keys…</h2></section>:state==="error"?<section className="data-panel console-state"><AlertTriangle/><h2>API keys could not be loaded</h2><Button variant="secondary" onClick={()=>void load()}>Retry</Button></section>:<section className="data-panel"><div className="key-table data-table" role="table" aria-label="Active API keys"><div className="data-row data-head" role="row">{["Name","Prefix","Environment","Scopes","Created","Last used","Status","Actions"].map((heading)=><span role="columnheader" key={heading}>{heading}</span>)}</div>{keys.map((key)=><div className="data-row" role="row" key={key.id}><strong role="cell">{key.name}</strong><code role="cell">{key.prefix}</code><span role="cell">{key.environment}</span><span role="cell">{key.scopes.join(", ")}</span><span role="cell">{key.created_at}</span><span role="cell">{key.last_used_at??"Never"}</span><span role="cell">{key.status}</span><span role="cell" className="row-actions"><button disabled={Boolean(busy)} onClick={()=>setConfirm({kind:"rotate",key})}><RefreshCw aria-hidden="true"/> Rotate</button><button disabled={Boolean(busy)} className="danger" onClick={()=>setConfirm({kind:"revoke",key})}><ShieldOff aria-hidden="true"/> Revoke</button></span></div>)}</div>{!keys.length&&<div className="empty-state"><KeyRound aria-hidden="true"/><h3>No API keys</h3><p>Create a scoped API key for your first integration.</p><Button onClick={()=>setCreating(true)}>Create API Key</Button></div>}</section>}
    <section className="key-lifecycle"><h2>API key lifecycle</h2><div><p><strong>Raw secret shown once</strong><span>The full value is never retrievable after dismissal.</span></p><p><strong>Only a verifier is stored</strong><span>WhitePact persists a one-way key hash and short prefix.</span></p><p><strong>Rotation creates a new key</strong><span>The previous key is revoked in the same transaction.</span></p><p><strong>Revocation is permanent</strong><span>Any later creation receives a new unique secret.</span></p></div></section>
    {creating&&<AccessibleDialog labelId="create-key-title" onClose={closeCreate}><header><h2 id="create-key-title">Create API key</h2><button onClick={closeCreate} aria-label="Close"><X/></button></header><form onSubmit={create}><label className="field"><span>Name</span><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} required /></label><label className="field"><span>Environment</span><select value={form.environment} onChange={(e)=>setForm({...form,environment:e.target.value})}><option value="test">Test</option><option value="live">Live</option></select></label><label className="field"><span>Expiration</span><select value={form.expires_in_days} onChange={(e)=>setForm({...form,expires_in_days:Number(e.target.value)})}><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>1 year</option></select></label><fieldset><legend>Scopes</legend>{["governance:read","governance:write","evidence:read","agents:read","agents:write"].map((scope)=><label className="checkbox" key={scope}><input type="checkbox" checked={form.scopes.includes(scope)} onChange={(e)=>setForm({...form,scopes:e.target.checked?[...form.scopes,scope]:form.scopes.filter((item)=>item!==scope)})}/><span>{scope}</span></label>)}</fieldset><Button disabled={busy==="create"}>{busy==="create"?"Creating…":"Create key"}</Button></form></AccessibleDialog>}
    {confirm&&<AccessibleDialog labelId="key-confirm-title" onClose={closeConfirm}><header><div><h2 id="key-confirm-title">{confirm.kind==="rotate"?"Rotate API key?":"Revoke API key?"}</h2><p>{confirm.key.name} · {confirm.key.prefix}</p></div><button onClick={closeConfirm} aria-label="Close"><X/></button></header><p>{confirm.kind==="rotate"?"A new secret will be created and the current key will stop working immediately.":"This key will stop working immediately. Revocation cannot be undone."}</p><div className="modal-actions"><Button variant={confirm.kind==="revoke"?"danger":"primary"} disabled={Boolean(busy)} onClick={()=>void mutate()}>{busy?"Submitting…":`Confirm ${confirm.kind}`}</Button><Button variant="secondary" disabled={Boolean(busy)} onClick={closeConfirm}>Cancel</Button></div></AccessibleDialog>}
    {created&&<AccessibleDialog labelId="key-created-title" onClose={closeReveal} className="key-reveal"><header><div><h2 id="key-created-title">API key created</h2><p>This is the only time the full secret is displayed.</p></div></header><code>{created.api_key}</code><div className="key-warning">Copy this key now. WhitePact will not display it again.</div>{copyState==="failed"&&<div className="form-error" role="alert">Clipboard access failed. Select and copy the key manually from the field above.</div>}<div className="modal-actions"><Button onClick={()=>void copy()}>{copyState==="copied"?<><Check/> Copied</>:<><Copy/> Copy API Key</>}</Button><Button variant="secondary" onClick={closeReveal}>Done</Button></div></AccessibleDialog>}
  </main>;
}
