# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT
"""Structured enterprise IAM error codes. Fail closed; never leak secrets."""

from __future__ import annotations


class EnterpriseError(Exception):
    def __init__(self, code: str, message: str, http_status: int = 403) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.http_status = http_status

    def as_detail(self) -> dict[str, str]:
        return {"error": self.code, "message": self.message}


UNAUTHENTICATED = "UNAUTHENTICATED"
FORBIDDEN = "FORBIDDEN"
WRONG_TENANT = "WRONG_TENANT"
WRONG_ENVIRONMENT = "WRONG_ENVIRONMENT"
KEY_REVOKED = "KEY_REVOKED"
KEY_EXPIRED = "KEY_EXPIRED"
INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE"
LAST_OWNER = "LAST_OWNER"
INVITE_EXPIRED = "INVITE_EXPIRED"
INVITE_REVOKED = "INVITE_REVOKED"
INVITE_REPLAY = "INVITE_REPLAY"
MEMBERSHIP_REVOKED = "MEMBERSHIP_REVOKED"
ORG_DISABLED = "ORG_DISABLED"
ORG_SUSPENDED = "ORG_SUSPENDED"
ENVIRONMENT_DISABLED = "ENVIRONMENT_DISABLED"
IDENTITY_VERIFICATION_REQUIRED = "IDENTITY_VERIFICATION_REQUIRED"
ORGANIZATION_VERIFICATION_REQUIRED = "ORGANIZATION_VERIFICATION_REQUIRED"
VERIFICATION_PENDING = "VERIFICATION_PENDING"
VERIFICATION_REVIEW_REQUIRED = "VERIFICATION_REVIEW_REQUIRED"
VERIFICATION_SUSPENDED = "VERIFICATION_SUSPENDED"
API_KEY_ISSUANCE_NOT_ALLOWED = "API_KEY_ISSUANCE_NOT_ALLOWED"
SERVICE_ACCOUNT_FORBIDDEN = "SERVICE_ACCOUNT_FORBIDDEN"
PROVIDER_SIGNATURE_INVALID = "PROVIDER_SIGNATURE_INVALID"
PROVIDER_REPLAY = "PROVIDER_REPLAY"
CROSS_TENANT = "CROSS_TENANT"
PASSKEY_REQUIRED = "PASSKEY_REQUIRED"
MFA_REQUIRED = "MFA_REQUIRED"
STEP_UP_REQUIRED = "STEP_UP_REQUIRED"
SSO_REQUIRED = "SSO_REQUIRED"
SSO_TENANT_MISMATCH = "SSO_TENANT_MISMATCH"
GOOGLE_WORKSPACE_MISMATCH = "GOOGLE_WORKSPACE_MISMATCH"
ENTRA_TENANT_MISMATCH = "ENTRA_TENANT_MISMATCH"
COMPANY_VERIFICATION_REQUIRED = "COMPANY_VERIFICATION_REQUIRED"
RECOVERY_REVIEW_REQUIRED = "RECOVERY_REVIEW_REQUIRED"
ACCOUNT_LINK_CONFLICT = "ACCOUNT_LINK_CONFLICT"
AUTHENTICATION_ASSURANCE_TOO_LOW = "AUTHENTICATION_ASSURANCE_TOO_LOW"
SECURITY_DOWNGRADE_BLOCKED = "SECURITY_DOWNGRADE_BLOCKED"
PHONE_VERIFIED_NOT_STRONG = "PHONE_VERIFIED_NOT_STRONG"
CHALLENGE_REPLAY = "CHALLENGE_REPLAY"
WEBAUTHN_INVALID = "WEBAUTHN_INVALID"
PROVIDER_TOKEN_INVALID = "PROVIDER_TOKEN_INVALID"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
BREAK_GLASS_DENIED = "BREAK_GLASS_DENIED"
LAST_AUTH_METHOD = "LAST_AUTH_METHOD"


def unauthenticated(message: str = "Authentication is required.") -> EnterpriseError:
    return EnterpriseError(UNAUTHENTICATED, message, 401)


def forbidden(code: str = FORBIDDEN, message: str = "Not permitted.") -> EnterpriseError:
    return EnterpriseError(code, message, 403)
