# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT

from __future__ import annotations

from enum import StrEnum


class EntityType(StrEnum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    AI_AGENT = "AI_AGENT"
    AI_MODEL = "AI_MODEL"
    MCP_SERVER = "MCP_SERVER"
    TOOL = "TOOL"
    PROJECT = "PROJECT"
    REPOSITORY = "REPOSITORY"
    DOMAIN = "DOMAIN"
    SOFTWARE_PACKAGE = "SOFTWARE_PACKAGE"
    API_SERVICE = "API_SERVICE"
    DATASET = "DATASET"


class EvidenceState(StrEnum):
    VERIFIED_FACT = "VERIFIED_FACT"
    INFERRED_SIGNAL = "INFERRED_SIGNAL"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class SourceQualityTier(StrEnum):
    AUTHORITATIVE_PRIMARY = "AUTHORITATIVE_PRIMARY"
    AUTHORITATIVE_REGISTRY = "AUTHORITATIVE_REGISTRY"
    FIRST_PARTY_PUBLICATION = "FIRST_PARTY_PUBLICATION"
    HIGH_QUALITY_SECONDARY = "HIGH_QUALITY_SECONDARY"
    COMMUNITY_SOURCE = "COMMUNITY_SOURCE"
    UNKNOWN_SOURCE = "UNKNOWN_SOURCE"


class FreshnessState(StrEnum):
    FRESH = "FRESH"
    AGING = "AGING"
    STALE = "STALE"
    REFRESH_REQUIRED = "REFRESH_REQUIRED"


class DataScope(StrEnum):
    GLOBAL_PUBLIC_EVIDENCE = "GLOBAL_PUBLIC_EVIDENCE"
    TENANT_PRIVATE_CONTEXT = "TENANT_PRIVATE_CONTEXT"


class SuppressionKind(StrEnum):
    DO_NOT_ENRICH = "DO_NOT_ENRICH"
    SUPPRESS_FIELD = "SUPPRESS_FIELD"
    SUPPRESS_ENTITY = "SUPPRESS_ENTITY"


class RelationshipPredicate(StrEnum):
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    CREATED = "CREATED"
    OWNS = "OWNS"
    OPERATES = "OPERATES"
    HAS_REPOSITORY = "HAS_REPOSITORY"
    PUBLISHES = "PUBLISHES"
    USES_MODEL = "USES_MODEL"
    INVOKES = "INVOKES"
    EXPOSES = "EXPOSES"
    HOSTED_ON = "HOSTED_ON"
