# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT
"""Evidence hints for AI-CAIQ v1.1 controls not in legacy CCM v4 map (261 keys)."""
from __future__ import annotations

SUPPLEMENT: dict[str, tuple[str, str, str]] = {}

def _set(qid: str, answer: str, ownership: str, desc: str) -> None:
    SUPPLEMENT[qid] = (answer, ownership, desc)

_set("AIS-08.1", "Yes", "CSP-owned", "REST/MCP auth: dashboard/app.py, src/responsibleai/mcp/ OAuth; tests/test_mcp_oauth.py, tests/test_mcp_oauth_authorization_server.py; .github/workflows/ci.yml.")
_set("AIS-08.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("AIS-09.1", "Yes", "CSP-owned", "Input guardrails: src/responsibleai/guardrails/engine.py; tests/test_streaming.py, tests/test_v1_api.py guardrail paths.")
_set("AIS-10.1", "Yes", "CSP-owned", "Output scanning: src/responsibleai/guardrails/engine.py; tests/test_streaming.py.")
_set("AIS-11.1", "Yes", "CSP-owned", "Agent execution boundaries: src/responsibleai/runtime/authority_kernel.py; tests/test_phase7a_authority_kernel.py.")
_set("AIS-12.1", "Yes", "CSP-owned", "PR + CI: .github/workflows/ci.yml (ruff, mypy, pytest); tests/test_whitepact_alias.py.")
_set("AIS-13.1", "No", "CSP-owned", "No dedicated OS-level sandbox for arbitrary AI plugins; MCP tool registry limits exposure only.")
_set("AIS-14.1", "No", "CSP-owned", "No GenAI-specific cache hardening beyond standard app caching.")
_set("AIS-15.1", "No", "CSP-owned", "No separate prompt-instruction delimiter contract across all model integrations.")
_set("BCR-02.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("CCC-06.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("DCS-03.3", "NA", "3rd-party outsourced", "WhitePact operates on cloud subprocessors (Render/Supabase/Upstash); no owned datacenter or physical media logistics. SSRM: cloud provider.")
_set("DCS-05.2", "NA", "3rd-party outsourced", "WhitePact operates on cloud subprocessors (Render/Supabase/Upstash); no owned datacenter or physical media logistics. SSRM: cloud provider.")
_set("DCS-06.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("DCS-10.2", "No", "CSP-owned", "No formal datacenter access-control log retention program.")
_set("DCS-16.1", "NA", "3rd-party outsourced", "WhitePact operates on cloud subprocessors (Render/Supabase/Upstash); no owned datacenter or physical media logistics. SSRM: cloud provider.")
_set("DCS-17.1", "NA", "3rd-party outsourced", "WhitePact operates on cloud subprocessors (Render/Supabase/Upstash); no owned datacenter or physical media logistics. SSRM: cloud provider.")
_set("DCS-18.1", "NA", "3rd-party outsourced", "WhitePact operates on cloud subprocessors (Render/Supabase/Upstash); no owned datacenter or physical media logistics. SSRM: cloud provider.")
_set("DSP-03.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("DSP-20.1", "Yes", "CSP-owned", "Data lineage inventory: src/responsibleai/data_governance/; tests/test_data_inventory.py.")
_set("DSP-21.1", "No", "CSP-owned", "No training-data poisoning detection for customer models.")
_set("DSP-22.1", "No", "CSP-owned", "No PET pipeline for customer training data.")
_set("DSP-23.1", "No", "CSP-owned", "WhitePact does not train foundation models on customer data.")
_set("DSP-23.2", "No", "CSP-owned", "No customer ML dataset versioning service.")
_set("DSP-24.1", "No", "CSP-owned", "Not applicable to product scope (governance platform, not model trainer).")
_set("GRC-07.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("GRC-09.1", "Yes", "CSP-owned", "AI acceptable use in GOVERNANCE.md, THREAT_MODEL.md, wiki/Home.md.")
_set("GRC-09.2", "No", "CSP-owned", "No continuous formal effectiveness review of AUP beyond code changes.")
_set("GRC-10.1", "No", "CSP-owned", "No standalone AI impact assessment process document.")
_set("GRC-11.1", "Yes", "CSP-owned", "Bias/fairness tooling: rai_* compliance tools; tests for governance modules in tests/test_v1_api.py.")
_set("GRC-12.1", "No", "CSP-owned", "No formal ethics committee — solo-founder governance.")
_set("GRC-13.1", "Yes", "CSP-owned", "Explainability requirements documented in compliance/ and product API responses (machine-readable).")
_set("GRC-14.1", "No", "CSP-owned", "Explainability limits not formally re-evaluated on a schedule.")
_set("GRC-15.1", "Yes", "CSP-owned", "Human oversight: governance/approval.py, runtime/authority_kernel.py; tests/test_resume_after_approval.py.")
_set("HRS-14.1", "No", "CSP-owned", "Organizational / people process not evidenced in repository operations.")
_set("HRS-14.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("HRS-15.1", "Yes", "CSP-owned", "GOVERNANCE.md acceptable-use for AI technologies.")
_set("I&S-01.1", "Yes", "CSP-owned", "ENTERPRISE_SECURITY.md, THREAT_MODEL.md, compliance/INTERNAL_SECURITY_REVIEW.md.")
_set("I&S-01.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("I&S-02.1", "No", "CSP-owned", "Capacity planning not formally monitored — provider-scaled.")
_set("I&S-03.1", "No", "CSP-owned", "No continuous mesh-wide comms monitoring beyond app logs.")
_set("I&S-03.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("I&S-04.1", "NA", "3rd-party outsourced", "Hypervisor/host hardening is cloud provider SSRM.")
_set("I&S-05.1", "Yes", "CSP-owned", "Config separation: dashboard/config.py; tests/test_pg_security_preservation.py; DEPLOY_RUNBOOK.md.")
_set("I&S-05.2", "No", "CSP-owned", "No documented prod-data sanitization pipeline for non-prod use.")
_set("I&S-06.1", "Yes", "CSP-owned", "Tenant isolation: tests/test_tenant_isolation.py, tests/test_phase5_tenant_isolation.py.")
_set("I&S-07.1", "NA", "3rd-party outsourced", "Physical/server migration channels are provider-operated.")
_set("I&S-07.2", "NA", "3rd-party outsourced", "Provider TLS protocol baselines; not WhitePact-operated migration.")
_set("I&S-08.1", "No", "CSP-owned", "No formal high-risk environment register.")
_set("I&S-09.1", "No", "CSP-owned", "No network-layer defense-in-depth program beyond app controls.")
_set("IAM-13.2", "No", "CSP-owned", "No enterprise PKI / cert-based service identities beyond TLS and OAuth tokens.")
_set("IAM-17.1", "Yes", "CSP-owned", "RBAC + approval for sensitive changes; tests/test_rbac.py.")
_set("IAM-18.1", "Yes", "CSP-owned", "MCP tool registry in src/responsibleai/mcp/; tests/test_mcp_production_tool_registry.py.")
_set("LOG-14.1", "Yes", "CSP-owned", "Monitoring: src/responsibleai/dashboard/prometheus.py; tests/test_telemetry.py.")
_set("LOG-14.2", "No", "CSP-owned", "No 24/7 accountable-party paging for all anomalies.")
_set("LOG-15.1", "No", "CSP-owned", "Audit logs metadata; not full AI model input content logging by default.")
_set("LOG-16.1", "No", "CSP-owned", "Audit logs metadata; not full AI model output content logging by default.")
_set("MDS-01.1", "No", "CSP-owned", "WhitePact does not host customer training pipelines.")
_set("MDS-01.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-02.1", "No", "CSP-owned", "No periodic model artifact scanning service.")
_set("MDS-02.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-03.1", "No", "CSP-owned", "No formal model documentation lifecycle for customer models.")
_set("MDS-03.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-04.1", "No", "CSP-owned", "No model documentation baseline for hosted models.")
_set("MDS-05.1", "No", "CSP-owned", "No model documentation validation workflow.")
_set("MDS-06.1", "No", "CSP-owned", "Adversarial ML testing not operationalized for customer models.")
_set("MDS-07.1", "No", "CSP-owned", "No model hardening program for customer checkpoints.")
_set("MDS-08.1", "No", "CSP-owned", "No checkpoint hash monitoring for customer models.")
_set("MDS-08.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-09.1", "No", "CSP-owned", "No cryptographic model signing pipeline.")
_set("MDS-10.1", "No", "CSP-owned", "No continuous model behavior monitoring for customer deployments.")
_set("MDS-11.1", "No", "CSP-owned", "No formal model failure risk evaluation service.")
_set("MDS-11.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-12.1", "No", "CSP-owned", "No open-model risk evaluation process.")
_set("MDS-12.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("MDS-13.1", "No", "CSP-owned", "No secure model serialization format enforcement.")
_set("SEF-08.2", "No", "CSP-owned", "No contractual material-breach notification SLA evidence.")
_set("SEF-09.1", "Yes", "CSP-owned", "Incident tracking via git/issues + compliance/csa-star-ai/INCIDENT_EXERCISE_REPORT.md (TABLETOP / SIMULATION).")
_set("SEF-09.2", "No", "CSP-owned", "No periodic formal review of incident record corpus.")
_set("SEF-10.1", "No", "CSP-owned", "Law-enforcement/regulator contact list not maintained.")
_set("SEF-10.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("STA-02.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("STA-09.2", "No", "CSP-owned", "No formal annual review cadence — policies updated with codebase changes. See GOVERNANCE.md; not calendar-driven operational proof.")
_set("STA-15.1", "No", "CSP-owned", "Subprocessor IT governance not reviewed annually — see SUBPROCESSOR_REGISTER.md.")
_set("STA-16.1", "Yes", "CSP-owned", "Supply chain: .github/workflows/security-scan.yml; compliance/VENDOR_RISK_ASSESSMENT.md.")
_set("TVM-04.2", "Yes", "CSP-owned", "THREAT_MODEL.md maintained; not calendar-reviewed.")
_set("TVM-11.1", "Yes", "CSP-owned", "GitHub issues/PRs + security-scan.yml for vulnerability tracking.")
_set("TVM-12.1", "No", "CSP-owned", "No formal vuln remediation metrics reporting cadence.")
_set("TVM-13.1", "Yes", "CSP-owned", "Guardrails: src/responsibleai/guardrails/engine.py; authority_kernel tests/test_phase7a_authority_kernel.py, tests/test_streaming.py.")
_set("TVM-13.2", "No", "CSP-owned", "Guardrails not continuously re-evaluated against regulatory changes.")

