# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT

"""Phase 2 remediation taxonomy (replaces UNCLASSIFIED)."""

from __future__ import annotations

from enum import StrEnum


class Phase2RemediationClass(StrEnum):
    SOURCE_CODE = "A_SOURCE_CODE"
    RUNTIME_ARCHITECTURE = "B_RUNTIME_ARCHITECTURE"
    INFRA_CONFIGURATION = "C_INFRA_CONFIGURATION"
    PRODUCTION_EVIDENCE = "D_PRODUCTION_EVIDENCE"
    CI_SUPPLY_CHAIN = "E_CI_SUPPLY_CHAIN"
    ORGANIZATIONAL = "F_ORGANIZATIONAL"
    CLOUD_SUBPROCESSOR = "G_CLOUD_SUBPROCESSOR"
    CUSTOMER_SHARED = "H_CUSTOMER_SHARED"
    LEGAL_PRIVACY = "I_LEGAL_PRIVACY"
    ENDPOINT_SECURITY = "J_ENDPOINT_SECURITY"
    MODEL_PROVIDER = "K_MODEL_PROVIDER"
    NOT_APPLICABLE_CANDIDATE = "L_NOT_APPLICABLE_CANDIDATE"
    OTHER_EXPLAINED = "M_OTHER_EXPLAINED"


class ImplementationState(StrEnum):
    IMPLEMENTED = "IMPLEMENTED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    PROVIDER_DEPENDENT = "PROVIDER_DEPENDENT"
    CUSTOMER_SHARED = "CUSTOMER_SHARED"
    HUMAN_EVIDENCE_REQUIRED = "HUMAN_EVIDENCE_REQUIRED"
    PRODUCTION_EVIDENCE_REQUIRED = "PRODUCTION_EVIDENCE_REQUIRED"


class CSARole(StrEnum):
    CSP = "CSP"
    MP = "MP"
    OSP = "OSP"
    AP = "AP"
    AIC = "AIC"
