#!/usr/bin/env python3
# Copyright (c) 2026 Guruprasath Annadurai
# SPDX-License-Identifier: MIT
"""Reject regressions in repository-controlled OpenSSF Scorecard controls.

This guard validates concrete controls; it never predicts or hardcodes a score.
Human history, repository age, GitHub scanner access, and external fuzzing runs
remain outside this script's evidence boundary.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
LOCKS = (
    "requirements-build.lock",
    "requirements-ci.lock",
    "requirements-container.lock",
    "requirements-security.lock",
)
SHA256_RE = re.compile(r"@sha256:[0-9a-f]{64}(?:\s|$)")


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def logical_lines(path: Path) -> list[tuple[int, str]]:
    """Join backslash-continued shell/Docker commands for policy inspection."""
    result: list[tuple[int, str]] = []
    current = ""
    start = 0
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = raw.strip()
        if not current and (not stripped or stripped.startswith("#")):
            continue
        if not current:
            start = number
        current = f"{current} {stripped}".strip()
        if current.endswith("\\"):
            current = current[:-1].rstrip()
            continue
        result.append((start, current))
        current = ""
    if current:
        result.append((start, current))
    return result


def main() -> int:
    failures: list[str] = []

    for name in LOCKS:
        path = ROOT / name
        if not path.is_file():
            failures.append(f"missing hash lock: {name}")
            continue
        content = path.read_text(encoding="utf-8")
        if "--hash=sha256:" not in content or "generated by uv" not in content.lower():
            failures.append(f"lock is not a generated hash lock: {name}")

    inspected = [ROOT / "Dockerfile", *sorted(WORKFLOWS.glob("*.y*ml"))]
    for path in inspected:
        for number, line in logical_lines(path):
            executable = line.split("#", 1)[0]
            if re.search(r"(?:python\s+-m\s+)?pip\s+install\b", executable):
                if "--require-hashes" not in executable:
                    failures.append(f"{path.relative_to(ROOT)}:{number}: unhashed pip install")

    for number, line in logical_lines(ROOT / "Dockerfile"):
        if line.startswith("FROM ") and not SHA256_RE.search(line):
            failures.append(f"Dockerfile:{number}: base image is not digest-pinned")

    for path in sorted((ROOT / "scripts").glob("*.sh")):
        for number, line in logical_lines(path):
            if re.search(r"\bdocker\s+run\b", line) and not SHA256_RE.search(line):
                failures.append(
                    f"{path.relative_to(ROOT)}:{number}: docker run image is not digest-pinned"
                )

    all_workflows = "\n".join(path.read_text(encoding="utf-8") for path in WORKFLOWS.glob("*.y*ml"))
    for event in ("pull_request_target:", "workflow_run:"):
        if event in all_workflows:
            failures.append(f"dangerous workflow trigger present: {event[:-1]}")
    if re.search(r"permissions:\s*(?:write-all|write)\b", all_workflows):
        failures.append("broad write workflow permission present")

    codeql = read(".github/workflows/codeql.yml")
    required_codeql = (
        "github/codeql-action/init@",
        "github/codeql-action/analyze@",
        "security-events: write",
        "languages: python",
    )
    for marker in required_codeql:
        if marker not in codeql:
            failures.append(f"CodeQL control missing: {marker}")

    builder = read(".github/workflows/reusable-build.yml")
    publish = read(".github/workflows/publish.yml")
    required_release = (
        (builder, "steps.provenance.outputs.bundle-path", "builder bundle output"),
        (builder, "-provenance.sigstore", "portable Sigstore asset"),
        (publish, "--bundle release-bundle/*-provenance.sigstore", "portable bundle verification"),
        (publish, "uses: ./.github/workflows/reusable-build.yml", "reusable release builder"),
    )
    for content, marker, description in required_release:
        if marker not in content:
            failures.append(f"release control missing: {description}")

    if failures:
        print("OpenSSF Scorecard regression guard failed:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print("Repository-controlled OpenSSF Scorecard regression controls are intact.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
