{{- if or .Values.config.apiKeys (and .Values.oidc.enabled (not .Values.oidc.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rai-governance.fullname" . }}
  labels:
    {{- include "rai-governance.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.apiKeys }}
  RAI_API_KEYS: {{ .Values.config.apiKeys | quote }}
  {{- end }}
{{- end }}
